### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by adamstep** [manufacturedba/team-member-management#1]
Hi @manufacturedba , thanks for the submission. I was not able to get the frontend running:
- In the main [README](http://localhost:4200), it says to run `./build` but I couldn't find that file in the repo.
- In the `frontend` directory, I followed the steps in the separate README and get this screen:

<img width="1313" alt="Screenshot 2024-09-17 at 9 40 32 AM" src="https://github.com/user-attachments/assets/50f0e12d-ca5a-485b-b4af-81ac108e3ee9">

**Comment by manufacturedba** [comment]
hey Adam, notes for scripts were just updated. They all live under `scripts/`

**Comment by adamstep** [comment]
Got it, was able to run the app now.
